### ISSUE TITLE
ZV vizitka

### ISSUE THREAD

**Issue by IxAriela** [nasajana/2022-ukol-02-vizitka#1]
Ahoj,

vypadá to dobře, technicky tam nemáš ani žádnou chybu :)

Ale pokud bys dostala zadání od zákazníka, tak je tam pár drobností, na které si dát pozor :)

- 2em není 36px. 2x16=32px. Máš tedy menší nadpis než bylo v zadání. Toto je drobnost, ale někteří grafici jsou i na toto dost citliví :)
- v zadání byla mezera od vrchního okraje 30px. Ty jsi ale nezrušila vrchni margin u nadpisu (ten je tam automaticky), takže je to víc, takových 50px.
- 30px má být mezera mezi druhým odstavcem a tlačítky, ale mezi odstavci by mělo být trošku méně (občas jsem si otevřela obrázek v gimpu/photoshopu a prostě měřila vzdálenosti) :)

Jsou to jen drobnosti, které nemusíš opravovat. Až si to přečteš, tak to můžeš uzavřít :)

**Comment by nasajana** [comment]
Moc děkuji za připomínky, je mi jasné, že i na drobnostech záleží a budu se snažit do budoucna vychytávat. :)
